# Generated by Django 2.1 on 2018-08-13 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='github_link',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='note',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='job',
            name='use_link',
            field=models.CharField(default='', max_length=100),
        ),
    ]
