# Generated by Django 2.1 on 2018-08-11 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('pub_date', models.DateField()),
                ('body', models.CharField(max_length=1600)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
